
export enum BgColors {
    Angular = "#b52e31",
    Docker = "#039cfd",
    DataScience = "#a0a9ba",
    PHP = "#7587bf",
    AI = "#9a2e7b",
    iOS = "#caf2b5",
    Security = "#99c2a2",
    Linux = "#e1bd18",
    DevOps = "#b5daf2",
    Git = "#f2f3f4",
    TypeScript = "#ff2ff",
    HTML = "#e46b48",
    CloudComputing = "#9fabe8",
    Ruby = "#cc342d",
    Java = "#fff",
    Kubernetes = "#e1eafb",
    JavaScript = "#f1e05a",
    WordPress = "#1ca7db",
    Blockchain = "#1d84cf",
    CMS = "#87CEEB",
    SQL = "#e0effe",
    Swift = "#ffac45",
    UXUI = "#5d5d5d",
  }